"use client";
import { useEffect } from "react";
import { useRouter } from "next/navigation";
import NavbarWrapper from "./components/NavbarWrapper"; // ใช้ NavbarWrapper แทน Navbar
import { Noto_Sans_Thai } from 'next/font/google';
import './globals.css';
const notoSansThai = Noto_Sans_Thai({
  subsets: ['thai', 'latin'],
  weight: ['100', '300', '400', '500', '700'],
  variable: '--font-noto-sans-thai',
});

// export const metadata = {
//   title: "WellWave",
//   description: "Generated by create next app",
//   icons: {
//     icon: "/wellwave.svg",
//     shortcut: "/welwave.svg"
//   }
// };

export default function RootLayout({ children }: { children: React.ReactNode }) {
  const router = useRouter();

  // ตรวจสอบการล็อกอินเฉพาะใน client-side
  useEffect(() => {
    const accessToken = localStorage.getItem("accessToken");

    if (!accessToken) {
      // ถ้าไม่มี accessToken ก็จะ redirect ไปที่หน้า login
      router.push("/login");
    }
  }, [router]);

  return (
    <html lang="en" className={notoSansThai.variable}>
      <body className={notoSansThai.variable}>
        <NavbarWrapper />
        {children}
      </body>
    </html>
  );
}
