sequenceDiagram
  actor Client as Learner
  participant CourseController
  participant CourseService
  participant CourseRepository

  Client->>+CourseController: GET /api/course/{courseCycle.id}/content
  
  CourseController->>+CourseService: getCourseContent()

  CourseService->>+CourseService: checkUserEnrollPermission()
  CourseService-->>-CourseService: permissionChecked
  
  alt User does not have permission
    CourseService-->>-CourseController: courseServiceResponse()
    CourseController-->>-Client: handleServiceResponse(failed)
  else User has permission
    activate CourseService
    CourseService->>+CourseRepository: getCourseCycleById()
    CourseRepository-->>-CourseService: courseCycle
    CourseService->>+CourseRepository: getCourseContentByCycleId()
    CourseRepository-->>-CourseService: courseContent
    CourseService-->>-CourseController: courseServiceResponse()
    activate CourseController
    CourseController-->>-Client: handleServiceResponse(success)
  end


