import { Noto_Sans_Thai } from 'next/font/google';
import '@/styles/globals.css';
import ClientProvider from '@/context/ClientProvider';
import { ThemeProvider } from 'next-themes';
import NavBar from '@/components/Main_navbar';
import dynamic from 'next/dynamic';

const MobileWarning = dynamic(() => import('@/components/MobileWarning'), {
  ssr: false,
});
const NotoSansTH = Noto_Sans_Thai({ subsets: ['latin'] });

export const metadata = {
  title: 'SQL Tutor',
  description: 'Generated by create next app',
  icons: [
    {
      rel: 'icon',
      type: 'image/png',
      sizes: '512x512',
      url: '/favicon/SQL.png',
    },
    {
      rel: 'icon',
      type: 'image/png',
      sizes: '256x256',
      url: '/favicon/SQL.png',
    },
    {
      rel: 'icon',
      type: 'image/png',
      sizes: '128x128',
      url: '/favicon/SQL.png',
    },
    {
      rel: 'apple-touch-icon',
      sizes: '180x180',
      url: '/favicon/apple-touch-icon.png',
    },
  ],
};

export default function RootLayout({ children }) {
  return (
    <html lang='en' suppressHydrationWarning={true}>
      <head>{/* push your head ups */}</head>
      <body className={NotoSansTH.className}>
        <ClientProvider>
          <ThemeProvider attribute='class' defaultTheme='light'>
            <div className='flex h-screen flex-col'>
              <NavBar />
              {children}
            </div>
            {/* userfor lazy fix style from mobile and tablet */}
            <div className='lg:hidden'>
              <MobileWarning />
            </div>
          </ThemeProvider>
        </ClientProvider>
      </body>
    </html>
  );
}
