export const studentsDetailedData = [
	{
		id: 1,
		studentId: '65015144',
		name: 'นายสมชาย ใจดี',
		quizzes: [
			{ chapter: 1, score: 2.5 },
			{ chapter: 2, score: 3 },
			{ chapter: 3, score: 2.5 },
			{ chapter: 4, score: 3 },
			{ chapter: 5, score: 2 },
			{ chapter: 6, score: 2.5 },
			{ chapter: 7, score: 3 },
			{ chapter: 8, score: 2.5 },
			{ chapter: 9, score: 2 },
			{ chapter: 10, score: 2 },
		],
		assignments: [
			{ name: 'Assignment 1', score: 18 },
			{ name: 'Assignment 2', score: 17 },
		],
	},
	{
		id: 2,
		studentId: '65015145',
		name: 'นางสาวสมหญิง รักเรียน',
		quizzes: [
			{ chapter: 1, score: 3 },
			{ chapter: 2, score: 3 },
			{ chapter: 3, score: 2.5 },
			{ chapter: 4, score: 3 },
			{ chapter: 5, score: 2.5 },
			{ chapter: 6, score: 2.5 },
			{ chapter: 7, score: 3 },
			{ chapter: 8, score: 2.5 },
			{ chapter: 9, score: 3 },
			{ chapter: 10, score: 2.5 },
		],
		assignments: [
			{ name: 'Assignment 1', score: 19 },
			{ name: 'Assignment 2', score: 19 },
		],
	},
	{
		id: 3,
		studentId: '65015146',
		name: 'นายวิชัย เรียนเก่ง',
		quizzes: [
			{ chapter: 1, score: 3 },
			{ chapter: 2, score: 2.5 },
			{ chapter: 3, score: 3 },
			{ chapter: 4, score: 2.5 },
			{ chapter: 5, score: 3 },
			{ chapter: 6, score: 2.5 },
			{ chapter: 7, score: 2.5 },
			{ chapter: 8, score: 3 },
			{ chapter: 9, score: 2.5 },
			{ chapter: 10, score: 3 },
		],
		assignments: [
			{ name: 'Assignment 1', score: 18 },
			{ name: 'Assignment 2', score: 18 },
		],
	},
	{
		id: 4,
		studentId: '65015147',
		name: 'นางสาวพิมพ์ใจ ตั้งใจ',
		quizzes: [
			{ chapter: 1, score: 2.5 },
			{ chapter: 2, score: 2 },
			{ chapter: 3, score: 2.5 },
			{ chapter: 4, score: 3 },
			{ chapter: 5, score: 2.5 },
			{ chapter: 6, score: 2 },
			{ chapter: 7, score: 2.5 },
			{ chapter: 8, score: 3 },
			{ chapter: 9, score: 2.5 },
			{ chapter: 10, score: 2.5 },
		],
		assignments: [
			{ name: 'Assignment 1', score: 17 },
			{ name: 'Assignment 2', score: 18 },
		],
	},
	{
		id: 5,
		studentId: '65015148',
		name: 'นายธนกร มุ่งมั่น',
		quizzes: [
			{ chapter: 1, score: 3 },
			{ chapter: 2, score: 2.5 },
			{ chapter: 3, score: 3 },
			{ chapter: 4, score: 2.5 },
			{ chapter: 5, score: 3 },
			{ chapter: 6, score: 2.5 },
			{ chapter: 7, score: 3 },
			{ chapter: 8, score: 2.5 },
			{ chapter: 9, score: 3 },
			{ chapter: 10, score: 2.5 },
		],
		assignments: [
			{ name: 'Assignment 1', score: 19 },
			{ name: 'Assignment 2', score: 18 },
		],
	},
	{
		id: 6,
		studentId: '65015149',
		name: 'นางสาวนภา ฟ้าใส',
		quizzes: [
			{ chapter: 1, score: 2 },
			{ chapter: 2, score: 2.5 },
			{ chapter: 3, score: 2 },
			{ chapter: 4, score: 2.5 },
			{ chapter: 5, score: 2 },
			{ chapter: 6, score: 2.5 },
			{ chapter: 7, score: 2 },
			{ chapter: 8, score: 2.5 },
			{ chapter: 9, score: 2 },
			{ chapter: 10, score: 2 },
		],
		assignments: [
			{ name: 'Assignment 1', score: 16 },
			{ name: 'Assignment 2', score: 17 },
		],
	},
	{
		id: 7,
		studentId: '65015150',
		name: 'นายภาคิน รักการเรียน',
		quizzes: [
			{ chapter: 1, score: 2.5 },
			{ chapter: 2, score: 3 },
			{ chapter: 3, score: 2.5 },
			{ chapter: 4, score: 3 },
			{ chapter: 5, score: 2.5 },
			{ chapter: 6, score: 3 },
			{ chapter: 7, score: 2.5 },
			{ chapter: 8, score: 3 },
			{ chapter: 9, score: 2.5 },
			{ chapter: 10, score: 3 },
		],
		assignments: [
			{ name: 'Assignment 1', score: 18 },
			{ name: 'Assignment 2', score: 19 },
		],
	},
	{
		id: 8,
		studentId: '65015151',
		name: 'นางสาวมินตรา ตั้งใจเรียน',
		quizzes: [
			{ chapter: 1, score: 3 },
			{ chapter: 2, score: 3 },
			{ chapter: 3, score: 3 },
			{ chapter: 4, score: 2.5 },
			{ chapter: 5, score: 3 },
			{ chapter: 6, score: 3 },
			{ chapter: 7, score: 2.5 },
			{ chapter: 8, score: 3 },
			{ chapter: 9, score: 3 },
			{ chapter: 10, score: 3 },
		],
		assignments: [
			{ name: 'Assignment 1', score: 19 },
			{ name: 'Assignment 2', score: 20 },
		],
	},
	{
		id: 9,
		studentId: '65015152',
		name: 'นายรัชชานนท์ ใฝ่รู้',
		quizzes: [
			{ chapter: 1, score: 2.5 },
			{ chapter: 2, score: 2 },
			{ chapter: 3, score: 2.5 },
			{ chapter: 4, score: 2 },
			{ chapter: 5, score: 2.5 },
			{ chapter: 6, score: 2 },
			{ chapter: 7, score: 2.5 },
			{ chapter: 8, score: 2 },
			{ chapter: 9, score: 2.5 },
			{ chapter: 10, score: 2 },
		],
		assignments: [
			{ name: 'Assignment 1', score: 17 },
			{ name: 'Assignment 2', score: 16 },
		],
	},
	{
		id: 10,
		studentId: '65015153',
		name: 'นางสาวลลิตา พากเพียร',
		quizzes: [
			{ chapter: 1, score: 2.5 },
			{ chapter: 2, score: 2.5 },
			{ chapter: 3, score: 2.5 },
			{ chapter: 4, score: 2.5 },
			{ chapter: 5, score: 2.5 },
			{ chapter: 6, score: 2.5 },
			{ chapter: 7, score: 2.5 },
			{ chapter: 8, score: 2.5 },
			{ chapter: 9, score: 2.5 },
			{ chapter: 10, score: 2.5 },
		],
		assignments: [
			{ name: 'Assignment 1', score: 18 },
			{ name: 'Assignment 2', score: 18 },
		],
	},
	{
		id: 11,
		studentId: '65015154',
		name: 'นายวรเมธ ขยันเรียน',
		quizzes: [
			{ chapter: 1, score: 3 },
			{ chapter: 2, score: 2.5 },
			{ chapter: 3, score: 3 },
			{ chapter: 4, score: 2.5 },
			{ chapter: 5, score: 3 },
			{ chapter: 6, score: 2.5 },
			{ chapter: 7, score: 3 },
			{ chapter: 8, score: 2.5 },
			{ chapter: 9, score: 3 },
			{ chapter: 10, score: 2.5 },
		],
		assignments: [
			{ name: 'Assignment 1', score: 19 },
			{ name: 'Assignment 2', score: 18 },
		],
	},
	{
		id: 12,
		studentId: '65015155',
		name: 'นางสาวศิริพร มานะ',
		quizzes: [
			{ chapter: 1, score: 2 },
			{ chapter: 2, score: 2.5 },
			{ chapter: 3, score: 2 },
			{ chapter: 4, score: 2.5 },
			{ chapter: 5, score: 2 },
			{ chapter: 6, score: 2.5 },
			{ chapter: 7, score: 2 },
			{ chapter: 8, score: 2.5 },
			{ chapter: 9, score: 2 },
			{ chapter: 10, score: 2 },
		],
		assignments: [
			{ name: 'Assignment 1', score: 16 },
			{ name: 'Assignment 2', score: 17 },
		],
	},
	{
		id: 13,
		studentId: '65015156',
		name: 'นายสุรเดช เพียรเรียน',
		quizzes: [
			{ chapter: 1, score: 2.5 },
			{ chapter: 2, score: 3 },
			{ chapter: 3, score: 2.5 },
			{ chapter: 4, score: 3 },
			{ chapter: 5, score: 2.5 },
			{ chapter: 6, score: 3 },
			{ chapter: 7, score: 2.5 },
			{ chapter: 8, score: 3 },
			{ chapter: 9, score: 2.5 },
			{ chapter: 10, score: 3 },
		],
		assignments: [
			{ name: 'Assignment 1', score: 1 },
			{ name: 'Assignment 2', score: 0 },
		],
	},
	{
		id: 14,
		studentId: '65015157',
		name: 'นางสาวอารยา ตั้งใจ',
		quizzes: [
			{ chapter: 1, score: 3 },
			{ chapter: 2, score: 3 },
			{ chapter: 3, score: 2.5 },
			{ chapter: 4, score: 3 },
			{ chapter: 5, score: 2.5 },
			{ chapter: 6, score: 3 },
			{ chapter: 7, score: 2.5 },
			{ chapter: 8, score: 3 },
			{ chapter: 9, score: 2.5 },
			{ chapter: 10, score: 3 },
		],
		assignments: [
			{ name: 'Assignment 1', score: 19 },
			{ name: 'Assignment 2', score: 18 },
		],
	},
];
