import type { IUserData } from '@/interfaces/user';

// user_id: number;
// email: string;
// firstname_th: string;
// lastname_th: string;
// firstname_en: string;
// lastname_en: string;
// role: string ];
// is_verified: boolean;
// is_active: boolean;

export const Users: IUserData[] = [
	{
		user_id: 0,
		email: 'ksjirasa@gmail.com',
		firstname_en: 'Jirasak',
		lastname_en: 'Sittigorn',
		firstname_th: 'จิรศักดิ์',
		lastname_th: 'สิทธิกรณ์',
		role: 'Admin',
		is_verified: true,
		is_active: true,
	},
	{
		user_id: 1,
		email: 'khthana@kmitl.ac.th',
		firstname_en: 'Thana',
		lastname_en: 'Hongsawan',
		firstname_th: 'ธนา',
		lastname_th: 'หงสุวรรณ',
		role: 'Instructor',
		is_verified: true,
		is_active: true,
	},
	{
		user_id: 2,
		email: 'bunditpp98@gmail.com',
		firstname_en: 'Bundit',
		lastname_en: 'Pasaya',
		firstname_th: 'บัณฑิต',
		lastname_th: 'พัสยา',
		role: 'Instructor',
		is_verified: false,
		is_active: true,
	},
	{
		user_id: 3,
		email: 'rathachai.ch@kmitl.ac.th',
		firstname_en: 'Rathachai',
		lastname_en: 'Chawuthai',
		firstname_th: 'รัฐชัย',
		lastname_th: 'ชาวอุทัย',
		role: 'Instructor',
		is_verified: true,
		is_active: true,
	},
	{
		user_id: 4,
		email: 'thanunchai.th@kmitl.ac.th',
		firstname_en: 'Thanunchai',
		lastname_en: 'Threepak',
		firstname_th: 'ธนัญชัย',
		lastname_th: 'ตรีภาค',
		role: 'Instructor',
		is_verified: true,
		is_active: true,
	},
	{
		user_id: 5,
		email: 'eiei0006@gmail.com',
		firstname_en: 'Thiraphat',
		lastname_en: 'Suksamosorn',
		firstname_th: 'ธีรภัทร์',
		lastname_th: 'สุขสโมสร',
		role: 'Learner',
		is_verified: true,
		is_active: true,
	},
	{
		user_id: 6,
		email: '001@gmail.com',
		firstname_en: 'soup01',
		lastname_en: 'bat01',
		firstname_th: 'soup01',
		lastname_th: 'bat01',
		role: 'Learner',
		is_verified: true,
		is_active: true,
	},
	{
		user_id: 7,
		email: '002@gmail.com',
		firstname_en: 'soup02',
		lastname_en: 'bat02',
		firstname_th: 'soup02',
		lastname_th: 'bat02',
		role: 'Learner',
		is_verified: true,
		is_active: true,
	},
	{
		user_id: 8,
		email: '003@gmail.com',
		firstname_en: 'soup03',
		lastname_en: 'bat03',
		firstname_th: 'soup03',
		lastname_th: 'bat03',
		role: 'Learner',
		is_verified: true,
		is_active: true,
	},
	{
		user_id: 9,
		email: '004@gmail.com',
		firstname_en: 'soup04',
		lastname_en: 'bat04',
		firstname_th: 'soup04',
		lastname_th: 'bat04',
		role: 'Learner',
		is_verified: true,
		is_active: true,
	},
	{
		user_id: 10,
		email: '005@gmail.com',
		firstname_en: 'soup05',
		lastname_en: 'bat05',
		firstname_th: 'soup05',
		lastname_th: 'bat05',
		role: 'Learner',
		is_verified: true,
		is_active: true,
	},
	{
		user_id: 11,
		email: '006@gmail.com',
		firstname_en: 'soup06',
		lastname_en: 'bat06',
		firstname_th: 'soup06',
		lastname_th: 'bat06',
		role: 'Learner',
		is_verified: true,
		is_active: true,
	},
	{
		user_id: 12,
		email: '007@gmail.com',
		firstname_en: 'soup07',
		lastname_en: 'bat07',
		firstname_th: 'soup07',
		lastname_th: 'bat07',
		role: 'Learner',
		is_verified: true,
		is_active: true,
	},
	{
		user_id: 13,
		email: '008@gmail.com',
		firstname_en: 'soup08',
		lastname_en: 'bat08',
		firstname_th: 'soup08',
		lastname_th: 'bat08',
		role: 'Learner',
		is_verified: true,
		is_active: true,
	},
	{
		user_id: 14,
		email: '009@gmail.com',
		firstname_en: 'soup09',
		lastname_en: 'bat09',
		firstname_th: 'soup09',
		lastname_th: 'bat09',
		role: 'Learner',
		is_verified: true,
		is_active: true,
	},
];
